name: 'Composite Action Recipe'
description: 'Greets the user and returns 42'
inputs:
  who-to-greet:
    description: 'Who to greet'
    required: true
    default: 'World'
outputs:
  answer:
    description: 'Answer to life, the universe, everything'
    value: ${{ steps.deep-though.outputs.answer }}
runs:
  using: "composite"
  steps:
    # - name: Awesome bash script Action
    #   id: deep-though
    #   shell: bash
    #   run: |
    #     echo "Hello '${{ inputs.who-to-greet }}'."
    #     echo "answer=42" >> $GITHUB_OUTPUT
    #     echo "So long, and thanks for all the fish!"
    - name: Awesome github script action
      uses: actions/github-script@v7.0.1
      with:
        script: |
          var whoToGreet: core.getInput('who-to-greet')
          core.notice(`Hello ${whoToGreet}`)
          core.setOutput('answer', 42)
          if (context.eventName == 'issues') {
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '👋 Thanks for reporting!'
            })
          }
      
